### ISSUE TITLE
Hangs after ' Enter phone number: '

### ISSUE THREAD

**Issue by delneg** [d99kris/nchat#1]
Couldn't find option to enable verbose logging, so i'm writing here

**Comment by d99kris** [comment]
Hi, thanks for reporting a bug.
1. Could you please share the content of your ~/.nchat/td.log ?
2. Did you enter your phone number with country code? I.e. if in U.S. like +16505551234 with the leading +1?
3. Do you have an existing Telegram account, or trying to register a new number?
Thanks,
Kris

**Comment by delneg** [comment]
1.
mbp-denis:build delneg$ cat ~/.nchat/td.log 
Using key: mi4JuEVsIWsytVaf
Using key: fTSfDsqB4HBeZcUF

2. Tried both
3. Existing account

**Comment by d99kris** [comment]
Thanks. Hmm I would expect the td.log to contain something more. Do you mind trying to run `nchat setup` again and see if there's some more in td.log? You can alter the actual data from td.log if your phone number or other personal info is there. 

To be honest you are probably the first user aside from myself. But I do use it daily without issues.

**Comment by d99kris** [comment]
And to clarify, the phone number should be entered with country code. After which you should be prompted to enter a confirmation code sent to your phone/telegram. 

I should probably add more documentation in the README regarding this.

**Comment by delneg** [comment]
I'm not the first, a couple of my friends are building it right now.
One is struggling with the same issue after build on OpenBSD.

I tried to enter phone in the format of +7903XXXXXXX

**Comment by delneg** [comment]
You should probably add much more verbose logging, as well as set logging param for tdlib to at least 14

**Comment by d99kris** [comment]
Thanks, it's probably a good idea to increase the logging verbosity. I'm on my phone now and won't get a chance to change that until I'm at my PC tomorrow evening. Btw, which OS are you using? Nchat is mainly developed/tested on macOS 14 Mojave and Ubuntu 18.04,

**Comment by delneg** [comment]
As you could've guessed from my shell prompt, i'm using macOS.
The version is 10.14 mojave as well

**Comment by d99kris** [comment]
Yep I did guess macOS, but just wanted to make sure. Thanks.

**Comment by d99kris** [comment]
Btw did you try to re-run `nchat setup` and see if td.log contained any additional stuff?
The "Using key" entry should only be there once authentication has been passed and nchat is started with plain `nchat` I think.

**Comment by delneg** [comment]
Yep, i did it at least 5 times. The only log is Using key: stuff

**Comment by d99kris** [comment]
Ok, thank you. I won't be able to do much today, but hopefully tomorrow. Will post updates here.

**Comment by d99kris** [comment]
I've implemented support for verbose logging. You can try running the setup with verbose logging enabled like this:
```
nchat --verbose --setup
```
Also, I'm wondering regarding your phone number example (+7903XXXXXXX) - is the country code +79? If yes, you can try to omit the first 0 after the country code. Or open the Telegram app on your phone, press menu button and check the number format shown there and use the same.

**Comment by d99kris** [comment]
No updates received the last 3 weeks, so I will proceed to close this issue. Feel free to re-open with additional log data if the issue persists.
