### ISSUE TITLE
Optional support for inline images/stickers

### ISSUE THREAD

**Issue by WeetHet** [d99kris/nchat#100]
### Discussed in https://github.com/d99kris/nchat/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **WeetHet** May 13, 2023</sup>
Some terminal emulators support viewing images using imgcat (or other similar tools). Would be great to see support for those here (as a configuration option).</div>

**Comment by d99kris** [comment]
Hi @WeetHet - for the `nchat` project we use `Issues` for bug reports and `Discussions` for feature requests and questions. Since you already posted a `Discussion` #99 for this feature, I will proceed to close this `Issue`.
