### ISSUE TITLE
The `--confdir` option is not functioning correctly.

### ISSUE THREAD

**Issue by lumpsoid** [d99kris/nchat#103]
**Description**:
When you use the `--confdir` option mentioned in the `--help` to specify a different folder for configuration loading, nchat displays the `--help` information instead of starting. However, when you use the `-d` option, everything works correctly.

**How to reproduce it**:
run in terminal:
`nchat --confdir ~/.config/nchat`
it will prints out `--help` information
![image](https://github.com/d99kris/nchat/assets/79290581/b2a1ef15-ff8a-4904-825d-6312794f5e73)

**Environment**:
- Version: 6.3.2-arch1-1
- OS / distro: Arch linux

**Comment by d99kris** [comment]
Hi @lumpsoid - thanks for reporting! It looks like this bug has been around for some time. Will look into fixing it soon.

**Comment by d99kris** [comment]
Hi again, this should be fixed now. Let me know if you're still facing any issues.

**Comment by lumpsoid** [comment]
Just confirming that the fix works

**Comment by d99kris** [comment]
> Just confirming that the fix works

Thanks for confirming 👍
