### ISSUE TITLE
add terminal bell for new messages in currently active chat

### ISSUE THREAD

**Issue by d99kris** [d99kris/nchat#11]
from issue #8 

> Send Terminal bell (control-G) for messages in chat that has focus - in nchat if the chat has focus, its greedy and marks the message as read even if the app does not have focus - denying the user notification that they got a message if its running in the background

**Comment by alohawolf** [comment]
I'd suggest that the bell_msg_any_chat should respect existing notification settings as set via other telegram clients - or a third setting can be added for that

**Comment by d99kris** [comment]
Thanks for catching @alohawolf - added a fix so nchat respects the notification setting.

**Comment by alohawolf** [comment]
How does this deal with @username mentions?

**Comment by d99kris** [comment]
> How does this deal with @username mentions?
No special treatment with respect to mentions in muted conversations (i.e. no bell). It's kind of consistent with the Telegram mobile app, which also wont show phone notifications for the same situation (I think).

**Comment by alohawolf** [comment]
telegram will notify on an @username mention even if group chat
notifications are turned off

**Comment by d99kris** [comment]
Looks like you're correct! My device didn't behave like this the other day for some reason. 

Anyway, nchat does not support this currently. Feel free to open an issue if you'd like to see this supported, and I'll see what can be done.
