### ISSUE TITLE
Chat in Chinese, there is always '^A' behind each character

### ISSUE THREAD

**Issue by ali-biz-gh** [d99kris/nchat#113]
**Description**:
Chat in Chinese, there is always '^A' behind each character
**How to reproduce it**:
Chat with your friend in Chinese, such as ‘你好'
then, it will show the '你^A好^A' in the chat history.

**Environment**:
- Version: 3.64
- OS / distro: ubuntu

**Comment by d99kris** [comment]
Hi @ali-biz-gh - can I check which terminal program you are using?
I'm not seeing this issue with `gnome-terminal` on Ubuntu 22.04 LTS.

**Comment by ali-biz-gh** [comment]
I use the fish shell on OS X and ssh into an AWS Ubuntu server to use 'nchat'.
https://fishshell.com/

```
stty -a
speed 38400 baud; 25 rows; 80 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

**Comment by ali-biz-gh** [comment]
<img width="588" alt="image" src="https://github.com/d99kris/nchat/assets/121898302/5f9ea5b0-c181-486d-bac7-344fb9b812c9">

**Comment by d99kris** [comment]
Hi @ali-biz-gh - I saw email notifications about some responses, but they are deleted now and you've closed the issue. I suppose you found a solution / workaround, if not feel free to re-open. 

Also, if you don't mind, feel free to share how you solved the problem, as it could help others encountering the same issue. Thanks!

**Comment by ali-biz-gh** [comment]
Thank you very much for your patience.
