### ISSUE TITLE
Whatsapp Enable flag not working

### ISSUE THREAD

**Issue by pavan-intelops** [d99kris/nchat#121]
**Description**:
After following the enabling WhatsApp steps provided in Readme, I can not see it in the `nchat -s` command result
**How to reproduce it**:

**Environment**: 
- Version: 18
- OS / distro: Ubuntu

**Comment by d99kris** [comment]
Hi @pavan-intelops - can I check what `go` version you're using, perhaps sharing the output from the following command:
```go version```
Also, when building `nchat`, do you get any warning message like:
```
$ ./make.sh build
-- Using -j2 (4 cores, 3000 MB phys mem, 1500 MB mem per core needed)
-- The CXX compiler identification is Clang 11.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using build type 'Release' (default).
-- Dummy: ON
-- Telegram: ON
-- WhatsApp: ON
-- Dynamic Load: ON
CMake Warning at CMakeLists.txt:58 (message):
  Go version 1.15.15 (need v1.18 to build WhatsApp).
```
If yes, it means you will need a newer go version (at least `1.18` for WhatsApp support).

**Comment by tomasmueller** [comment]
I try installing on Ubuntu 20.04 with go version 1.13. I updated to go version 1.20 using this howto: https://tecadmin.net/how-to-install-go-on-ubuntu-20-04/

```
go version
go version go1.20.2 linux/amd64
```

Now i have the error:

```
cmake -DHAS_WHATSAPP=ON .. && make -s
CMake Error: The source directory "/home/user" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

When i copy the CMakeLists.txt from the build subdir to my home dir and run cmake again i have this errors:

```
cmake -DHAS_WHATSAPP=ON .. && make -s
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using build type 'Release' (default).
-- Dummy: ON
-- Telegram: ON
-- WhatsApp: ON
-- Dynamic Load: ON
CMake Error at CMakeLists.txt:129 (add_subdirectory):
  add_subdirectory given source "lib/ncutil" which is not an existing
  directory.


CMake Error at CMakeLists.txt:131 (add_subdirectory):
  add_subdirectory given source "lib/duchat" which is not an existing
  directory.
 ...

```

**Comment by d99kris** [comment]
Hi, it looks like `cmake` was being run from the wrong directory. Also, whatsapp is enabled by default (if `go` >= v1.18 is present) so no need to specify the flag. So when you're in the cloned folder `nchat` you can just run:
```
mkdir -p build && cd build && cmake .. && make -s
```
And if you want to install:
```
sudo make install
```

**Comment by d99kris** [comment]
Alternatively, for simpler commands you can use the build-script used for nchat CI. While in the cloned folder `nchat`:
```
./build.sh make
```
And to install:
```
./build install
```

**Comment by d99kris** [comment]
One final note is that I would maybe recommend removing the `build` folder if your environment changed (like installing a new `go` version) to make sure the build script picks up the latest information. If you're unsure about this step, the easiest way to ensure a clean build is to simply remove the entire `nchat` directory and do a fresh git clone.

**Comment by tomasmueller** [comment]
OK, works on Ubuntu 20.04.

I want to run the command line from time to time and save messages, attachments and status images. But there isn't a command line option for that.

**Comment by d99kris** [comment]
> OK, works on Ubuntu 20.04.

Great to hear, thanks for sharing.

> I want to run the command line from time to time and save messages, attachments and status images. But there isn't a command line option for that.

Right, `nchat` is primarily an interactive application, so there's not much support for automation. Automation is basically out of scope for this project. There might be other WhatsApp clients that supports such things, I don't keep track of that though. 

I will proceed to close this bug, as the basic issue is resolved. Feel free to re-open if you have follow-up questions/issues.
