### ISSUE TITLE
Configurable and dynamic online status

### ISSUE THREAD

**Issue by d99kris** [d99kris/nchat#127]
### Discussed in https://github.com/d99kris/nchat/discussions/122

<div type='discussions-op-text'>

<sup>Originally posted by **samtrek** September  4, 2023</sup>
How does nchat handle offline and online status to other normal whatsapp users? Seems my own nchat whatsapp is always online, which is a function that I dont desire, I have looked through the options to see if I can see an option to turn it off, I have not seen any, is there anyway not to show always online to other users?</div>

**Comment by d99kris** [comment]
This has been implemented in above commit, please check the README for these three new settings:
- online_status_share
- online_status_dynamic
- typing_status_share

**Comment by Bellavene** [comment]
I don't even know, but I believe the answer is — always online.

**Comment by d99kris** [comment]
> I don't even know, but I believe the answer is — always online.

Yep, with a default nchat installation it always present user as online while nchat is running. I created this issue from a discussion (see #122) to add support for more flexibility, where one can turn off online status, or just have nchat show as online while terminal is active.
