### ISSUE TITLE
Way to ignore a contact or status@broadcast?

### ISSUE THREAD

**Issue by orxaz** [d99kris/nchat#131]
### Discussed in https://github.com/d99kris/nchat/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **orxaz** September 25, 2023</sup>
Hi!

Thanks for your nice work.

I would like to ask you if there is a way to ignore a chat. That I want is not to enter and download/see all states from the people when I hit the status@broadcast conversation when using WhatsApp.

Thanks!</div>

**Comment by d99kris** [comment]
For this project I prefer to keep questions and feature requests in the discussion section.

If a feature request is accepted / planned I might "create an issue" from the discussion to track it's implementation (especially if it's not a quick fix).

I'll close this issue for now, but I'll leave the discussion open until I have time to look into it a bit more.
