### ISSUE TITLE
Cannot copy example themes - path does not exist

### ISSUE THREAD

**Issue by snckrz** [d99kris/nchat#139]
**Description**:
i cant copy the example themes with the command from the readme 
` cp /usr/local/share/nchat/themes/basic-color/* ~/.nchat/ ` Because the path doesn't seem to exist.
I am using a M1 mac and installed via homebrew.

**Environment**:
- Version: 3.67
- OS / distro: macos Sonoma 14.0

**Comment by d99kris** [comment]
Hi @snckrz - thanks for reporting the issue. Looks like the documentation is outdated and not applicable for M1 / Mac Silicon. I'll look into updating the README. Meanwhile you can try copying example themes like this:
```bash
cp $(dirname $(which nchat))/../share/nchat/themes/basic-color/* ~/.nchatd/
``` 
Will leave this issue open until I've pushed a fix updating the README.

**Comment by d99kris** [comment]
The README have been updated in above commit. Please let me know if you're still facing any issues using the example themes. Thanks!
