### ISSUE TITLE
Colors not shown in tmux

### ISSUE THREAD

**Issue by snckrz** [d99kris/nchat#141]
**Description**:
There seems to be no support for colors, when running nchat inside of tmux. 
Im not sure if its a config error on my end, however, other apps (htop) or angular cli seem to have no trouble with color output.
**How to reproduce it**:
run nchat in tmux
**Environment**:
- Version: 3.67
- OS / distro: macOS 14.0

**Comment by d99kris** [comment]
Hi @snckrz - I'm not sure, but I believe it might be an incompatibility between ncurses and tmux.

As a temporary workaround, perhaps you can try setting the `TERM` you have outside tmux, i.e. if outside tmux you run `echo $TERM` and it returns `xterm-256color`, then when running nchat you can try run it like this:
```
TERM=xterm-256color nchat
```

From some quick googling, it is not the right way to do so, but I think it may do as a temporary workaround.

**Comment by d99kris** [comment]
I've added the workaround to the README, closing this issue.
