### ISSUE TITLE
Compiling on Void Linux - fatal error: td/telegram/td_api.h

### ISSUE THREAD

**Issue by johnwuelk** [d99kris/nchat#142]
Is there an installation instruction for Void?

**How to reproduce it**: 
1.  Install dependencies (is there maybe something missing here?): 
`xbps-install -Su  go ccache cmake gperf help2man libmagick-devel readline-devel sqlite-devel file-devel `
2. `git clone https://github.com/d99kris/nchat && cd nchat`
3. `mkdir -p build && cd build && cmake .. && make -s`

```
[ 91%] Building CXX object lib/tgchat/CMakeFiles/tgchat.dir/src/tgchat.cpp.o
In file included from /home/jo/Downloads/nchat-3.67/nchat-3.67/lib/tgchat/src/tgchat.cpp:20:
/home/jo/Downloads/nchat-3.67/nchat-3.67/lib/tgchat/ext/td/td/telegram/Client.h:11:10: fatal error: td/telegram/td_api.h: No such file or directory
   11 | #include "td/telegram/td_api.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib/tgchat/CMakeFiles/tgchat.dir/build.make:76: lib/tgchat/CMakeFiles/tgchat.dir/src/tgchat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:412: lib/tgchat/CMakeFiles/tgchat.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Environment**:
- Version: nchat-3.67
- OS / distro: Void Linux

**Comment by d99kris** [comment]
Hi @johnwuelk - I'll see if I can try building on Void Linux. Meanwhile, could you share if you're using [musl](https://docs.voidlinux.org/installation/musl.html) or **glibc** installation of Void? Also knowing the amount of RAM on the system and whether it's 64-bit could be useful. Finally if you could share the compiler version `c++ --version` and also the full output when building (might need to save in a txt file and drag into the comment field to attach), it would be very helpful. Thanks!

The list of dependencies looks ok, I think only `base-devel` is missing (and possibly `git` if downloading via git).

**Comment by d99kris** [comment]
Hi @johnwuelk - I finally got a chance to take a closer look at this and to try Void. It appears `openssl-devel` is missing. If the build still fails after installing `openssl-devel`, could you please provide the full output from the build command, for example:

    ./make.sh build >> log.txt 2>&1

I'll add documentation for Void dependencies in the README, and also support for Void in the `./make.sh deps` command for installing dependencies.

**Comment by d99kris** [comment]
The README and `make.sh` script have been updated in above commit. Feel free to re-open this issue if you're still facing issues building nchat on Void.
