### ISSUE TITLE
Can't seem to disable Online Status Share

### ISSUE THREAD

**Issue by EttVenter** [d99kris/nchat#143]
**Description**:

Not sure where I'm going wrong, but I can't disable this. When I add "online_status_share=0" to my ui.conf, and then run the app, my status is still shared, and the moment I quit nchat, that line is removed from the ui.conf file. 

What am I doing wrong here?

**Environment**: iTerm2, 

- OS / distro: MacOS Ventura

**Comment by d99kris** [comment]
Hi @EttVenter - can I check what version of nchat you're using? (`nchat -v` should output it)

Configurable and dynamic online status was added fairly recently, in v3.68 / 28bec95.

Let's say if you're installing nchat via brew, you'll be using the latest official stable release, which currently is v3.67. FYI the next stable release is at the end of every quarter.

**Comment by EttVenter** [comment]
I just did all of this but I can't figure out how to run it. Hahaha. Sorry, I'm a total noob. All your steps worked, but how do I run it?

**Comment by d99kris** [comment]
Okay 🙂  The commands listed would've uninstalled the brew installation of nchat, and then installed it from your source clone instead. It should be possible to run just `nchat` in a terminal now. If you're getting
```nchat: command not found```
it's possible the default installation directory for nchat is not in your `PATH`, so then you can try run it like this:
```/usr/local/bin/nchat```
or alternatively update your `PATH` to be able to simply run `nchat`. How to do that depends on what your shell is (zsh, bash, etc) I think. For me (using `bash`) I would edit `~/.bash_profile` and add a line line 
```
export PATH=$PATH:/usr/local/bin"
```
Hope this helps!

**Comment by d99kris** [comment]
Just in case the above doesn't work, you can re-run `./make.sh install` from the nchat source clone directory, and check the output which would have output like:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/nchat
-- Installing: /usr/local/lib/libncutil.dylib
-- Installing: /usr/local/lib/libduchat.dylib
-- Installing: /usr/local/lib/libtgchat.dylib
```
The line ending with `/nchat` would be the one saying where it has been installed, i.e. in the above example
```
/usr/local/bin/nchat
```

**Comment by EttVenter** [comment]
This all worked perfectly. Thank you so much for all your help, and thank you for helping me with even the basics here. Haha. Love your app!

**Comment by d99kris** [comment]
No probs, great to hear it worked 👍
