### ISSUE TITLE
`downloads_dir` cannot create a directory, and files are downloaded before user confirmation

### ISSUE THREAD

**Issue by Kabouik** [d99kris/nchat#158]
**Description**:
The `downloads_dir` option cannot create a directory, and will default to `~/Downloads` if the set path does not exist. This can be an issue if the user wants to download to a `/tmp` subfolder for instance. It gracefully falls back to `~/Downloads`, but does not show a warning or create the missing directory, which I think would  be best.

Also, when pressing `^R` to download a file, there is a prompt indicating the path and asking to cancel or confirm, but files are downloaded even when cancelling. This is the case at least for attachments sent with `attachment_send_type=0`, but perhaps other attachments too.

**Environment**:
- Version: 3.97
- OS / distro: Droidian

**Comment by d99kris** [comment]
Hi @Kabouik - I've added support for creating `downloads_dir` if specified directory does not exist.

As for the the downloading of files, the dialog is intended to just be a notification message (so the user knows where the file ended up, and with what name). Thus, I've removed showing the "cancel" key binding in the help bar when showing this notification.

**Comment by Kabouik** [comment]
Great, thanks!
