### ISSUE TITLE
Brew install - repo not found

### ISSUE THREAD

**Issue by LemuelCushing** [d99kris/nchat#159]
**Description**:
Trying to install using brew raises the following error:

```
brew install d99kris/d99kris/nchat
==> Tapping d99kris/d99kris
Cloning into '/opt/homebrew/Library/Taps/d99kris/homebrew-d99kris'...
remote: Repository not found.
fatal: repository 'https://github.com/d99kris/homebrew-d99kris/' not found
Error: Failure while executing; `git clone https://github.com/d99kris/homebrew-d99kris /opt/homebrew/Library/Taps/d99kris/homebrew-d99kris --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

**How to reproduce it**:
Just run `brew install d99kris/d99kris/nchat`

**Environment**:
- OS / distro: Sonoma

**Comment by d99kris** [comment]
Hi @LemuelCushing - thanks for reporting this issue! Apparently this error snuck in when I updated the installation instructions in 4b71a18. Please try these steps instead to install using brew on macOS:
```
brew tap d99kris/nchat
brew install nchat
```
I'll try to get the README updated as soon as a I get a chance.

**Comment by d99kris** [comment]
The README has been updated in above commit.
