### ISSUE TITLE
Telegram contact name is not immediately updated upon rename from other client

### ISSUE THREAD

**Issue by wedcanto** [d99kris/nchat#160]
**Description**:
If I rename a contact in another telegram client (Telegram desktop), the old name is displayed in nchat.
**How to reproduce it**:
rename any contact in telegram desktop, and check that in nchat this contact has the old name
**Environment**: 
- Version:
- OS / distro: Ubuntu 22.04, xfce, tilix

**Comment by d99kris** [comment]
How fast do you see the updated name reflected on your phone after updating your contact name using Telegram desktop?

I only did some quick tests, but it seems it is not updated, unless I go and open that particular chat on the phone. Do you see the same?

**Comment by d99kris** [comment]
Hi @wedcanto - I've found no indication that Telegram servers send out updates to clients when one of them rename a contact. I don't think it would be ideal for nchat to poll for contact name updates. As such I'll consider this out-of-scope for now.

You may report a feature request if you wish, and maybe it can be added to the project scope/functionality one day (as an optional feature to poll, disabled by default), although I think the chance is quite low unfortunately.
