### ISSUE TITLE
Can't paste the char `ă` in entry box 

### ISSUE THREAD

**Issue by ta2013** [d99kris/nchat#164]
Can't input/paste the char ă into the entry box.

Thanks.

**Comment by d99kris** [comment]
If you run nchat in key dump mode, `nchat -k`, and paste the character (ex: `ă`) you can see what it maps to on your system. On my Mac it is `\403 KEY_UP`.

Assuming that's the case on your system, you can run `nchat -k` and find some other key you'd like to use for "up", and then replace `KEY_UP` with that key in `~/.nchat/key.conf` (or if you don't use `KEY_UP` you could just remove it, but then you cannot access all functionality, so..).

It's a little strange though, that `ă` has same key code as `KEY_UP`. Can I check what's your output if you run `locale` in the terminal?

**Comment by d99kris** [comment]
Doing a little more research on this, it seems there is a way for an application using ncurses to differentiate between `ă` and `KEY_UP`. I will look into how to fix this in `nchat`. Will update here again once I've found a solution.

**Comment by d99kris** [comment]
Pasting of ă should be fixed in above commit. Thanks for reporting this issue!
