### ISSUE TITLE
Admin Deletion of Other Messages not Working

### ISSUE THREAD

**Issue by arcxne** [d99kris/nchat#167]
**Description**:
I saw a discussion saying that admins delete messages of other users. To test this, I opened a whatsapp chat I am an admin of in nchat and attempted to delete another person's message. While this normally works in Whatsapp, it doesn't work in nchat.

The popup to delete the message also doesn't ask if I want to delete for myself or for everyone, albeit I expected it to do so. Maybe nchat doesn't know that I'm an admin?
Also, I'm not sure if it's supposed to, but deleting the message only deletes it on nchat, but I can still view that message in the Whatsapp app.

**How to reproduce it**:
Open chat > ctrl-d to delete message > press RETURN for popup asking if you want to delete message

**Environment**:
- Version: 3.67
- OS / distro: MacOS 14.1.1

**Comment by d99kris** [comment]
Hi @arcxne - `whatsapp support for group admin deletion of messages sent by others` was added in #148 / 02f91fc / v3.97. Your version (v3.67) does not have the fix.

If you are sticking to stable releases of nchat, the next one is planned for end Q4, so then you can get the functionality. Alternatively you can switch to using latest git master. You'll get fixes and features faster, but it may at times be unstable (I try to minimize this though).

I will proceed to close this issue, as it's already been fixed, but feel free to post any follow-up questions here, or re-open this issue if it still doesn't work after upgrading to >= v3.97. Thanks!
