### ISSUE TITLE
Contacts shown duplicated for WhatsApp after setup

### ISSUE THREAD

**Issue by Disonantemus** [d99kris/nchat#170]
**Description**:
I did try nchat 4 1st time today with whatsapp, 1st setup launch did ok, but when finally showing contacts and messages, 1d8 CPU cores got 100%, and nchat got non-responsive, then I did quit, restart, now I do have a working responsive nchat, but all my contacts are duplicated. If I restart again, contacts are still duplicated.

**How to reproduce it**:
1. launch nchat.
2. watch contact list, all are duplicated.
3. show address book (^n).

**Environment**:
- Version: 4.13 (GIT)
- OS / distro: OS: Arch Linux x86_64 / Kernel: 6.5.3-arch1-1

---

If I show address book (^n), I get something like this:
~~~
┌───────────────────── Select Contact ─────────────────────┐
│ . @ WhatsAppMd_+541143823353                             │
│ . @ WhatsAppMd_+54 11 4382 3353^[[D^[[                   │
│ . @ WhatsAppMd_+541143823353                             │
│ . @ WhatsAppMd_+54 11 4382 3353^[[D^[[                   │
│ 530×16✊💣💰💸💸 @ WhatsAppMd_+541143823353              │
│ 530×16✊💣💰💸💸 @ WhatsAppMd_+54 11 4382 3353^[[D^[[    │
│ 946011 @ WhatsAppMd_+54 11 4382 3353^[[D^[[              │
│ 946011 @ WhatsAppMd_+541143823353                        │
~~~
Note1: I did change phone numbers 4 privacy reasons, but you get the idea, contacts appear 2 times, one with phone number separated and one altogether.

Note2: There's also those trailing `^[[D^[[`, that appears like a escape codes, that appear at the duplicated contact.

---

There's maybe another bug related to this, when pressing TAB to go next chat, sometimes you see next contact highlighted and return to previous, you get that when pressing TAB many times. Theories:
- Same bug previous described.
- When message is not locally cached.

**Comment by d99kris** [comment]
Hi @Disonantemus - are you sure you only performed the setup (`nchat -s`) once?

In any case, as a workaround, you could try deleting the config directory (`rm -rf ~/.nchat` unless you have a custom path) and setup again. This time let nchat run for a while even if it appears hung. The whatsapp first sync takes a bit of time, on my system/connection about 15-20 secs, but others may be slower.

Based on the address book "screenshot" you shared, it appears that nchat has been set up twice for whatsapp, once for number `+541143823353` and once for `+54 11 4382 3353^[[D^[[` (effectively the same number). It's probably a bug that nchat allows that to happen (it could strip spaces and control characters), but in any case, the end result is that you are logged in twice with same account from nchat, so all your contacts are shown twice, and other things are probably not going to work well as well.

**Comment by Disonantemus** [comment]
- I did try as you said, removing `.nchat` folder and did setup again.
- This time again get a 100% CPU (1d8 cores), but wait a lot (3-5min) till all CPU cores gets a reasonable load bellow (5-10%).
- My connection is fiber optics, is not so slow, maybe your machine is a lot faster, mine is an older i7-4790.
- Now works as expected with no duplicated contacts.
- I did restart and no problem.

---

- Then, maybe I did quit nchat when setup didn't complete, and that introduce a bug from next launch.
- It could be helpful to show a warning message, to not quit setup process, and a message when setup is done.
- Also some checks to warn user to do again setup when detecting duplicated contacts.
- Thank you, this fix my issue!

**Comment by d99kris** [comment]
I've added some fixes (two commits above) to reduce the risk of running into the reported issue:
- Phone number entered is "cleaned up", so only digits and + are kept
- A confirmation dialog is shown if trying to exit during initial sync
