### ISSUE TITLE
CMake Generate step keeps failing

### ISSUE THREAD

**Issue by ebenezerArt** [d99kris/nchat#174]
### Discussed in https://github.com/d99kris/nchat/discussions/173

<div type='discussions-op-text'>

<sup>Originally posted by **ebenezerArt** December 22, 2023</sup>
![image](https://github.com/d99kris/nchat/assets/70277659/bbd6a6b8-267f-4ff3-9b1a-b755ae59f460)

How do I set the variable build testing to FOUND and not NOTFOUND.

.....or any other way to get this warning from going away.
</div>

**Comment by d99kris** [comment]
This does not appear to be a bug in nchat, but rather in brew or brew packaging of libmagic. In either case I will proceed to close this issue, and we can track further troubleshooting of the problem under #173 discussion.
