### ISSUE TITLE
[Enhancement] Add support for non-UTF-8 locales

### ISSUE THREAD

**Issue by saahriktu** [d99kris/nchat#20]
nchat doesn't perform character set conversion between current locale and server side UTF-8 (for example, over iconv()). It makes impossible to use nchat with locales other than UTF-8.

**Comment by d99kris** [comment]
May I know the output of `locale` on your system? And also which terminal app/emulator in use, as well as OS? Just so I can try out a similar environment.

I'm not sure whether the line-drawing capabilities of ncursesw used by nchat can work with any locale, so there's a possibility it will be difficult to support, but I can look into it.  

Btw, do things work fine if you force nchat to a UTF-8 locale, as in `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 nchat` (all on one line) or does your terminal emulator not support it?

**Comment by saahriktu** [comment]
I use linux console (vt) with ru_RU.KOI8-R locale. ncurses with setlocale(LC_ALL, ""); works fine, but text need to be converted to proper codepage.

**Comment by d99kris** [comment]
Thanks! I haven't had time to look into this yet. I've mainly used UTF8 for my recent projects and I'm not really familiar with the best practise for supporting non-UTF8. If you know some other open-source software or two that handles this correctly, feel free to share the names, then I can look at those source codes to see what they do. Or feel free to submit a PR. :)

**Comment by saahriktu** [comment]
>If you know some other open-source software or two that handles this correctly, feel free to share the names, then I can look at those source codes to see what they do.
lynx, irssi, lftp, links, bitlbee,... etc

**Comment by d99kris** [comment]
Great, thanks!

**Comment by d99kris** [comment]
After some consideration I've decided to leave non-UTF8 as out of scope for nchat. However, should someone prepare a pull request with the necessary changes I will be open reviewing and accepting/pulling it, as long as it's not too complex. Closing this issue for now.
