### ISSUE TITLE
First alt/opt key press may result in wrong text input

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#210]
**Description**:
Opt+Right writes [1;9C on first press. On next presses, it behaves as it should, without any additional text in text entry.

**Environment**:
- Version: 14.0
- OS / distro: macos
- Terminal: iTerm 3.4.20

**Comment by Bellavene** [comment]
Managed by itself

**Comment by d99kris** [comment]
Hi @Bellavene - actually I can reproduce a similar issue on my side. If I start nchat and press alt-c twice, I see `c` in the text entry field. Will re-open this issue and prepare a fix.

**Comment by d99kris** [comment]
The above commit should fix the issue. Please let me know if you still encounter problems.

**Comment by Bellavene** [comment]
Hallo, Kris! Thank You. Instant bug fixes, as always <3
