### ISSUE TITLE
[Feature request] Add hide password Two-Step verification

### ISSUE THREAD

**Issue by deevroman** [d99kris/nchat#22]

**Comment by d99kris** [comment]
This makes sense. I don't use that functionality myself so I never reflected over that it echoed the entered password on the terminal. 

For reference - during the setup of a Telegram with two-factor authentication, the following password prompt should hide the entered password:
```
Enter authentication password:
```

**Comment by d99kris** [comment]
Dev notes: Can probably use something like this GetPass() implementation:  https://github.com/d99kris/nmail/blob/master/src/util.cpp#L754
