### ISSUE TITLE
Difficulties with installing on Pop! OS

### ISSUE THREAD

**Issue by austinoneil** [d99kris/nchat#226]
**Description**: When installing on Pop! OS, I got the issue "deps failed (unsupported linux distro ${NAME}), exiting.".  When replacing [this check](https://github.com/d99kris/nchat/blob/master/make.sh#L129) with just a "true", it installs just fine.

**How to reproduce it**: Install on Pop! OS.  A virtual machine should work for this.

**Environment**:
- Version:
- OS / distro:

**Comment by d99kris** [comment]
Hi @austinoneil - thanks for reporting an issue. I will look into adding handling of Pop! OS.

**Comment by d99kris** [comment]
Handling of Pop! OS has been added in above commit.
