### ISSUE TITLE
[WhatsApp] Edited messages via app don't update in nchat

### ISSUE THREAD

**Issue by fulalas** [d99kris/nchat#227]
If I edit a message on WhatsApp app on my phone and then open nchat, the version of the message that I see in nchat is the old/original one, not the edited one.

Version: `4.75`

**Comment by d99kris** [comment]
Hi @fulalas - thanks for reporting a bug. I can see the issue here too. I will look into preparing a fix.

**Comment by d99kris** [comment]
WhatsApp handling for edited messages has been added now, let me know in case you still encounter any issues. Thanks!

**Comment by fulalas** [comment]
It's fixed, thanks!

I noticed something peculiar though. If I send a message via nchat and try to edit it using WhatsApp app, I can't. The edit option doesn't even show up. Can you replicate this?

**Comment by d99kris** [comment]
I can see that issue too. I'm not sure what the cause is. Possibly due to some WhatsApp protocol updates which the reverse-engineered library does not yet handle. I'm planning to soon (~few weeks) update to a newer version of the whatsapp library, will see if that resolves this issue.
