### ISSUE TITLE
Some remaps are broken after selecting contact

### ISSUE THREAD

**Issue by bg16-2009** [d99kris/nchat#235]
**Description**:
After selecting a contact using ctrl+n, some custom remaps don't work until I restart the app

**How to reproduce it**:
- Install nchat from the AUR
- Run the setup (using whatsapp)
- Set the following keys in key.conf (alt + h j k l instead of arrows):
```
up=\33\153
down=\33\152
left=\33\150
right=\33\154
```
- Run nchat
- Select a contact
- After selecting a contact, try to use alt + h j k l to navigate between messages
- You get a rectangle in the message box
- NOTE: When selecting contacts, the keymaps work as expected

**Environment**:
- Version: v4.41
- OS / distro: Arch linux
- Terminal: kitty

**Comment by d99kris** [comment]
Hi @bg16-2009 - thanks for reporting an issue. There was a fix for this type of issue in v4.44, see #193 for details.

Please try v4.44 or a newer version. In AUR there's an `nchat-git` package providing latest version from git: `yay -S nchat-git`

If you're sticking to the `nchat` stable package, the next release will be end June.

**Comment by bg16-2009** [comment]
Thanks a lot for the quick reply! I installed `nchat-git` and everything works as expected.

**Comment by d99kris** [comment]
Great 👍
