### ISSUE TITLE
Can't edit WhatsApp messages anymore

### ISSUE THREAD

**Issue by fulalas** [d99kris/nchat#236]
Even when sending a message using nchat I can no longer edit them. I'm aware of the 15 minutes limit, but that's not the case. It was working until few days ago.

For Telegram protocol it works perfectly.

nchat 4.79

**Comment by d99kris** [comment]
Hi @fulalas - that's strange. I don't have any issues editing sent message from `nchat` (irrespective of whether the original message is sent from nchat or official phone app), confirmed just now. 

Could you help check if there are any warnings or errors in the nchat log file? And does nchat show any error dialog, or allow you to edit but then the actual message is just not updated?

**Comment by fulalas** [comment]
Damn, my bad, sorry. My localtime symlink got broken when I updated my machine.

nchat rocks!
Thanks!
