### ISSUE TITLE
[Enhancement] Sorted chats based on last activity

### ISSUE THREAD

**Issue by jfamousket** [d99kris/nchat#24]
Firstly, Great Work!!!
I just have a few problems:

   - I would like for the chats to be sorted in terms of the last message received i.e. I want the chat with the newest message to be at the top of the chat list 
   - I would like to have an unread messages count beside the chat name instead of a *.

I am willing to make updates on my personal clone if you can point me to where to make these updates (I am not used to C : /).
Thanks.

**Comment by d99kris** [comment]
Thanks for reporting the suggestions, I think they make sense.

To enable sorted chats some "architectural" changes are needed, so unfortunately I can't provide some simple pointers. But I'll look into this. I've also missed this functionality sometimes. 

The counter for unread messages should be more simple, but I don't have the code fresh in my head now so I'll need to take a look.

**Comment by jfamousket** [comment]
Thanks for your timely reply, looking forward to the changes.

**Comment by d99kris** [comment]
Hi @jfamousket - the architectural changes has finally been completed - and nchat has been rewritten essentially from scratch in e5b20c0. Chats are now sorted based on last message timestamp, similar to the phone app.

Message count is not available, as it is complex to report correctly. Feel free to submit a new Github issue if you still would like to see this supported. I will close this issue.
