### ISSUE TITLE
whatsapp client outdated

### ISSUE THREAD

**Issue by gilcu3** [d99kris/nchat#248]
**Description**:
I am getting this on the logs since a few hours ago:
```
2024-06-04 10:31:47.786 | ERROR | whatsmeow Client outdated (405) connect failure (client version: 2.2404.5)  (gowm.go:455)
2024-06-04 10:31:47.786 | WARN  | Client Outdated  (gowm.go:828)
2024-06-04 10:31:47.858 | WARN  | state not connected 4  (gowm.go:1775)
2024-06-04 10:31:47.886 | ERROR | whatsmeow Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF  (gowm.go:455)
2024-06-04 10:31:56.174 | WARN  | Failed to send presence  (gowm.go:2278)
```

Does that mean that `whatsmeow` needs to be updated in `nchat`, or might be something else (network issue on my side)?

**Environment**:
- Version: `master`
- OS / distro: `Archlinux`

**Comment by d99kris** [comment]
Hi @gilcu3 - thanks for reporting the issue and providing logs. This issue should be resolved with dbc056e (whatsmeow has been updated), it's available in the latest nchat v4.86 - just released https://github.com/d99kris/nchat/releases/tag/v4.86 

Let me know if you still encounter any issues after updating to latest nchat. Thanks!

**Comment by gilcu3** [comment]
Thank you very much for the quick fix @d99kris, now it works without issues!

**Comment by hseg** [comment]
This fixed it for me as well.

Question -- is there a reason you're shipping a copy of whatsmeow directly, instead of using one of git's mechanisms for embedding a repo in a repo[1][2][3]? (even if you don't use them fully, at least you could simplify `utils/*-update` to only do the patching). Not using these mechanisms made eg this commit unusually noisy.

[1]: https://git-scm.com/docs/git-submodule
[2]: https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt
[3]: https://github.com/ingydotnet/git-subrepo

**Comment by d99kris** [comment]
I prefer to keep the code repository "version control system agnostic", and the main reason being able to release a snapshot of current source tree as a tar-ball which can be built/installed using standard commands (`mkdir build ; cd build; cmake ..; make`). Currently source releases are made using Github's release function - and I _believe_ it does not include submodules automatically (although this might have changed in recent years). 

Also, although this is less relevant [now in 2024](https://github.blog/2023-01-20-sunsetting-subversion-support/), Github used to support SVN access (actually I used this back during the first year or so of nchat development), which IIRC did not handle git submodules. 

Anyway, given that nchat needs it's own modifications to whatsmeow (and the above reasons) I feel the pros outweight the cons, using the current approach.

**Comment by hseg** [comment]
OK! Hadn't considered that design direction before, but makes quite some sense, thanks for the detailed explanation.
