### ISSUE TITLE
Whatsmeow outdated

### ISSUE THREAD

**Issue by SeeStarz** [d99kris/nchat#283]
**Description**: nchat is offline, whatsmeow is probably outdated
```
2024-08-23 10:54:50.063 | INFO  | nchat v4.88  (main.cpp:249)
2024-08-23 10:54:50.063 | INFO  | Arch Linux x86_64  (main.cpp:251)
2024-08-23 10:54:50.063 | INFO  | GCC 14.1.1 20240720 glibc 2.40  (main.cpp:253)
2024-08-23 10:54:50.063 | INFO  | Go 1.22.5  (main.cpp:255)
2024-08-23 10:54:50.063 | INFO  | Telegram ON, WhatsApp ON  (main.cpp:257)
2024-08-23 10:54:50.068 | INFO  | load whatsapp profile  (wmchat.cpp:118)
2024-08-23 10:54:50.071 | INFO  | ui loop start  (ui.cpp:95)
2024-08-23 10:54:55.856 | ERROR | whatsmeow Client outdated (405) connect failure (client version: 2.2412.50)  (gowm.go:455)
2024-08-23 10:54:55.857 | WARN  | Client Outdated  (gowm.go:828)
2024-08-23 10:54:55.948 | WARN  | state not connected 4  (gowm.go:1775)
2024-08-23 10:54:55.986 | ERROR | whatsmeow Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EOF  (gowm.go:455)
2024-08-23 10:54:56.503 | WARN  | Failed to send presence  (gowm.go:2278)
2024-08-23 10:54:56.554 | WARN  | Failed to send presence  (gowm.go:2278)
2024-08-23 10:54:57.553 | INFO  | ui loop end  (ui.cpp:108)
2024-08-23 10:54:57.553 | WARN  | Failed to send presence  (gowm.go:2278)
2024-08-23 10:54:57.655 | INFO  | exit  (main.cpp:432)
```

**How to reproduce it**: run nchat

**Environment**:
- Version: 4.88
- OS / distro: Arch Linux

**Comment by d99kris** [comment]
Hi @SeeStarz - thanks for reporting this bug! I will prepare a new release tomorrow which fixes the issue.

As you're on Arch, if you need a workaround, you can uninstall the `nchat` package and install `nchat-git` instead. But if you can wait, there will be a release tomorrow, and the `nchat` AUR package will likely be updated shortly thereafter.

**Comment by d99kris** [comment]
Btw, were you using nchat OK daily before this bug?

I'm just trying to get an idea of how often I need to release nchat going forward. It seems like whatsapp/facebook has shortened their expiration before a client becomes outdated, so the previous quarterly release cycle for nchat will not be sufficient.

**Comment by ksketo** [comment]
@d99kris FWIW I have been using it daily for the last 3-4 weeks.

**Comment by Jack-Kaller** [comment]
Hi @d99kris, I'm using nchat daily for about 2 months and I encountered the bug yesterday. If it helps !

**Comment by darleisantossoares** [comment]
I still can't use chat :(

**Comment by d99kris** [comment]
nchat [v5.1.29](https://github.com/d99kris/nchat/releases/tag/v5.1.29) has now been released, i.e. the source code package. I've also updated the [homebrew package](https://github.com/d99kris/homebrew-nchat).

Regarding the [Arch / AUR nchat package](https://aur.archlinux.org/packages/nchat) I've flagged it out-of-date, but I am not sure when it will be updated.

**Comment by SeeStarz** [comment]
actually i had a little bug with it not rendering some text correctly (leftovers from other texts) though i'm uncertain how to report it, and i'm not sure how to reproduce it either. 
apart from that it has been working very well for the last couple weeks. 
regarding the nchat-git package, i saw that on the github page that last change are a couple weeks back. so i assume the difference between nchat-git and nchat is how they fetch dependencies? i'll keep in mind to switch to git version if it breaks anytime in the future.

**Comment by SeeStarz** [comment]
> nchat [v5.1.29](https://github.com/d99kris/nchat/releases/tag/v5.1.29) has now been released, i.e. the source code package. I've also updated the [homebrew package](https://github.com/d99kris/homebrew-nchat).
> 
> Regarding the [Arch / AUR nchat package](https://aur.archlinux.org/packages/nchat) I've flagged it out-of-date, but I am not sure when it will be updated.
> 
> **Edit:** Thanks for providing the data points on usage and when it stopped working. I'll adjust the release cycle for nchat in order to try avoid this issue in the future.

It's already updated and working, thanks!

**Comment by d99kris** [comment]
> It's already updated and working, thanks!

Great 👍 

> actually i had a little bug with it not rendering some text correctly (leftovers from other texts) though i'm uncertain how to report it, and i'm not sure how to reproduce it either.

I think there may be issues with certain emojis in certain terminal emulators, causing something like leftover text. I think red heart (❤️) might be one such emoji - there was some discussion in #279. 

> regarding the nchat-git package, i saw that on the github page that last change are a couple weeks back. so i assume the difference between nchat-git and nchat is how they fetch dependencies? 

The AUR package `nchat-git` will always point to the latest code in `nchat` `master` branch (currently it's `v5.2.1`) irrespective of the `Last Updated` timestamp on the AUR package page. The `nchat` AUR package on the other hand, points to the latest stable `nchat` release (currently it's `v5.1.29`). Previously this was a quarterly release, but I will probably change it to be monthly instead, due to the WhatsApp client getting outdated faster nowadays.
