### ISSUE TITLE
[Suggestion] Contact list sorting options

### ISSUE THREAD

**Issue by IronPiston** [d99kris/nchat#29]
Currently, it appears that contacts are sorted via groups then private messages. Two features would make contact sorting more robust:

1) Respect pinned chats, sorting them at the top of the list at all times
2) Option to sort chronologically, rather than by group size

With both of these, chats should sort the same way as Telegram does.

**Comment by d99kris** [comment]
Hi @IronPiston  - improved chat sorting (sorted by last message timestamp) has been implemented in e5b20c0.

**Comment by Disonantemus** [comment]
- This fixed `#2` sorting by timestamp.
- But still today (nchat 4.13 GIT) don't address `#1` , I do think is useful (whatsapp side).

**Comment by d99kris** [comment]
> * This fixed `#2` sorting by timestamp.
> * But still today (nchat 4.13 GIT) don't address `#1` , I do think is useful (whatsapp side).

Right, pinned chats are not supported by nchat (yet). There's a feature request for it #168 - please help to upvote it if you'd like to see it supported.

**Comment by Disonantemus** [comment]
- Thanks, I will.
- I didn't see that, because I did a "pinned" search at Issues only, my mistake.

**Comment by d99kris** [comment]
Thanks, and no worries! I know it's not typical to split bugs under "issues" and feature requests under "discussions". It just helps me to separate urgent from nice-to-have tasks.
