### ISSUE TITLE
Fix android termux build of whatsapp

### ISSUE THREAD

**Issue by d99kris** [d99kris/nchat#292]
### Discussed in https://github.com/d99kris/nchat/discussions/284

<div type='discussions-op-text'>

<sup>Originally posted by **John4650-hub** August 23, 2024</sup>
> Is it possible to install this tool on android with termux?
</div>

Basic build support (for Telegram) in Android Termux was added in #286. 

This issue to add support for building WhatsApp as well.

Note: For setting up a WhatsApp profile in nchat under Termux running on a phone, it will be useful to ssh into it, so that the authentication Qr code can be viewed on a different device, and scanned using the phone in the WhatsApp app.

**Comment by d99kris** [comment]
To build nchat (with Telegram and WhatsApp support) under Termux, one must set certain build flags (`HAS_DYNAMICLOAD=OFF` and `HAS_STATICGOLIB=OFF`). The following commands can be used:
```
pkg install cmake clang golang ccache gperf file readline libsqlite openssl
git clone https://github.com/d99kris/nchat && cd nchat
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} -DHAS_DYNAMICLOAD=OFF -DHAS_STATICGOLIB=OFF ..
make -sj8
make install
```

**Comment by samtrek** [comment]
I tired building it with termux, the error thrown is given below

Configuring done (0.3s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files: WORDEXP_LIBRARY 
linked by target "ncutil" in directory /data/data/com.termux/files/home/nchat/lib/ncutil
CMake Generate step failed.  Build files cannot be regenerated correctly

**Comment by d99kris** [comment]
Hi @samtrek - try run this to install wordexp:
```
pkg install libandroid-wordexp
```
I'll update the steps in my comment on Sep 7.
