### ISSUE TITLE
[Suggestion] Colors for various elements

### ISSUE THREAD

**Issue by IronPiston** [d99kris/nchat#30]
Colored text would make reading chats and distinguishing UI elements much easier.

I would suggest adding color to the following elements:
- Name of the person who sent message
- URLs
- Titles generated from Telegram Instant View
- Documents
- Stickers
- Date
- Time
- Contacts in side pane

Of course it would be nice if the colors could be changed in a config rather than an element like URL being hardcoded as blue.

**Comment by d99kris** [comment]
Hi @IronPiston  - basic support for color customization has been implemented in e5b20c0.
