### ISSUE TITLE
Build error in MessagesManager when installing via Arch AUR package

### ISSUE THREAD

**Issue by retroflexivity** [d99kris/nchat#301]
Hi,

An error occurs while building on Arch.

The log is
```
[400/522] Building CXX object lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o
FAILED: lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o 
/usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/td/generate/auto -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/tdnet -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/tdutils -I/home/retroflexivity/.cache/yay/nchat-git/src/build/lib/tgchat/ext/td/tdutils -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/tdactor -I/home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/tddb -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -std=c++14 -fno-omit-frame-pointer -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wall -Wextra -Wimplicit-fallthrough=2 -Wpointer-arith -Wcast-qual -Wsign-compare -Wduplicated-branches -Wduplicated-cond -Walloc-zero -Wlogical-op -Wno-tautological-compare -Wpointer-arith -Wvla -Wnon-virtual-dtor -Wno-unused-parameter -Wconversion -Wno-sign-conversion -Wdeprecated -Wodr -flto-odr-type-merging -Wno-psabi -Wno-maybe-uninitialized -Wno-redundant-move -Wno-stringop-overflow -std=gnu++14 -fPIC -MD -MT lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o -MF lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o.d -o lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o -c /home/retroflexivity/.cache/yay/nchat-git/src/nchat/lib/tgchat/ext/td/td/telegram/MessagesManager.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[409/522] Building CXX object lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/NotificationManager.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: nchat-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
nchat-git - exit status 4
```

I have no idea what it means, but I'll be glad to provide more details.

**Environment**:
- Version: Linux 6.11.1-arch1-1
- OS / distro: EndeavourOS x86_64

**Comment by d99kris** [comment]
Hi @retroflexivity - can I check how much RAM your system has?

For the Telegram protocol nchat used the official [tdlib](https://github.com/tdlib/td) which requires a bit of RAM - around ~3.5GB RAM to build using G++ and ~1.5GB RAM with clang++. If your RAM is around those sizes please see [Building on Low Memory / RAM Systems](https://github.com/d99kris/nchat/blob/master/doc/LOWMEMORY.md) or if you're only interested in WhatsApp support, you can disable Telegram protocol altogether - see [Feature Flags](https://github.com/d99kris/nchat/blob/master/doc/FLAGS.md).

**Comment by retroflexivity** [comment]
It has 8 GB, I guess this should be enough? But I'll try

The manual for Arch says I should `Change the `_install_mode` to `slow``, but I don't see the parameter in PKGBUILD. Where do I put it?

**Comment by d99kris** [comment]
8 GB should be enough, then it's not a memory problem, so ignore those suggestions I shared in the previous reply.

**Comment by d99kris** [comment]
What command are you using to build / install nchat btw?

**Comment by retroflexivity** [comment]
I've tried `yay -S` and `makepkg -s`. In fact, RAM usage does seem to reach 100%.

**Comment by d99kris** [comment]
Is that `yay -S nchat-git` or `yay -S nchat`?

I suspect there could be some issue with the Arch packaging build script, I am not maintaining that myself, but I can try check its code.

If you need a quick workaround, building from source may work:
```
git clone https://github.com/d99kris/nchat && cd nchat
./make.sh deps
./make.sh build && ./make.sh install
```
The reason being that the source build script `make.sh` tries to adjust the build memory usage based on system RAM and compiler in use.

**Comment by retroflexivity** [comment]
> Is that `yay -S nchat-git` or `yay -S nchat`?

I'm pretty certain I've tried both.

I've just built it from source, it worked fine. Thank you

**Comment by d99kris** [comment]
> I've just built it from source, it worked fine. Thank you

Good to hear! 👍 

I'll leave this issue open until I've checked if the AUR package PKGBUILD script can be updated to fix this.

**Comment by d99kris** [comment]
`nchat-git` is the latest yes, it uses head of master branch from this source repository.

`nchat` points to latest stable release (generally released at the end of each quarter).

I am not 100% sure about Arch Linux AUR packaging, but I believe the `Last Updated` fields in their respective pages ([nchat](https://aur.archlinux.org/packages/nchat) and [nchat-git](https://aur.archlinux.org/packages/nchat-git)) refers to when the package "formula" was updated. For `nchat` I suspect it needs to be updated for every new stable release, but for `nchat-git` it always points to just "latest", so it seldom needs to be updated (unless say the dependencies of nchat upstream has changed).

**Comment by d99kris** [comment]
> also i just installed the git package and didnt face any error

Ok thanks for the data point. The out of memory issue encountered by the OP is due to having less than 3.5 GB RAM per logical CPU core (or thread), required by tdlib (a nchat dependency). The AUR package scripts do not take into account this memory requirement. I'll check with the package maintainers if we can add handling for it.

**Comment by retroflexivity** [comment]
mine is i5-1135G7

**Comment by fulalas** [comment]
> The out of memory issue encountered by the OP is due to having less than 3.5 GB RAM per logical CPU core (or thread), required by tdlib (a nchat dependency).

I just built here watching `/proc/meminfo` and the peak memory usage (discount what the system was already using) was 4.3 GB using 16 threads and golang + clang. Although heavy, this is pretty much doable on a 8 GB machine.

**Comment by d99kris** [comment]
As a workaround you can try building / installing from source as described [here](https://github.com/d99kris/nchat/issues/301#issuecomment-2393952368) - I have yet to check on Arch packaging scripts.

**Comment by d99kris** [comment]
I checked the Arch AUR packages now, and apparently they used to use nchat `make.sh` build script (which adjusts number of concurrent build jobs, and thus memory requirements, based on system RAM and compiler) but switched to calling cmake directly this year; [nchat](https://aur.archlinux.org/cgit/aur.git/commit/?h=nchat&id=4862a82ff25fa3b9a95588221c7207dca2ddbcfc), [nchat-git](https://aur.archlinux.org/cgit/aur.git/commit/?h=nchat-git&id=81e45307a1dd896351b3e0bed93d7e0301100f94)

They probably made the change for some good reason, so I would suggest report the build error issue to them. I believe AUR packaging issues are reported by adding comments on their pages, i.e. https://aur.archlinux.org/packages/nchat or https://aur.archlinux.org/packages/nchat-git

**Comment by d99kris** [comment]
I will proceed to close this issue for now, but feel free to add comments if there are any updates on Arch AUR side.

**Comment by themarcman314** [comment]
I was also encountering this issue on an 8GB machine as well.
Finding this issue helped, thank you!
Hopefully this gets fixed sometime.
