### ISSUE TITLE
key.conf reverts to default config

### ISSUE THREAD

**Issue by guthubrx** [d99kris/nchat#311]
**Description**:
Hello
What ever the changes I make in key.conf, this file reverts to default as soon as i start nchat

**How to reproduce it**:
For instance, a vim edit of ~/.config/nchat/key.conf
react=\33\163 to react=KEY_CTRLB
start nchat  : reverted to react=\33\163

**Environment**:
- Version: 31
- OS / distro: Macos Sonoma 15.0.1

However great whatsapp client ! Thank you !

**Comment by d99kris** [comment]
Hi @guthubrx - were you by any chance running `nchat` while editing the key.conf file? 

Currently `nchat` reads its config files on startup and writes them back at exit (thus overwriting any changes made in other editor while it was running). One can argue that this behavior is suboptimal, but it's to be consistent with how it handles its other config files, which have parameters that can be reconfigured from nchat itself.

**Comment by guthubrx** [comment]
I was indeed, you nailed it ! Now it works like charm, thank you !
