### ISSUE TITLE
unable to setup (error code 406)

### ISSUE THREAD

**Issue by recrunchi** [d99kris/nchat#46]
hi, i just installed this app on my debian box and i cannot set it up.

log:
starting nchat v2.14 
auth error "error {
  code = 406
  message = "UPDATE_APP_TO_LOGIN"
}

related issue: https://github.com/LonamiWebs/Telethon/issues/3215 ...
... "Telegram has started enforcing the use of 64-bit identifiers for users and chats, and the current stable version of the library does not support them yet. If you try to login, you may see UPDATE_APP_TO_LOGIN error."

**Comment by skate4lol** [comment]
same error, updated whole linux system and telethon... already on 1.24 still cant get my programs to work

**Comment by skate4lol** [comment]
this helped me you should give it a try 

"Ok thanks.. i have fixed this :) just upgraded my PyroGram"

**Comment by recrunchi** [comment]
> this helped me you should give it a try
> 
> "Ok thanks.. i have fixed this :) just upgraded my PyroGram"

sorry, i can't understand you.. what you did?

**Comment by skate4lol** [comment]
> > this helped me you should give it a try
> > "Ok thanks.. i have fixed this :) just upgraded my PyroGram"
> 
> sorry, i can't understand you.. what you did?

"pip3 install PyroGram"

or if you already got it installed
"pip3 upgrade PyroGram"

**Comment by recrunchi** [comment]
> > > this helped me you should give it a try
> > > "Ok thanks.. i have fixed this :) just upgraded my PyroGram"
> > 
> > 
> > sorry, i can't understand you.. what you did?
> 
> "pip3 install PyroGram"
> 
> or if you already got it installed "pip3 upgrade PyroGram"

i just installed it, and no luck. nchat log keeps saying: error 406 UPDATE_APP_TO_LOGIN

**Comment by alohawolf** [comment]
Related issue:

https://github.com/tdlib/td/issues/1758

**Comment by d99kris** [comment]
Thanks @alohawolf - looks like we need to update the `tdlib` version `nchat` uses.

I'm preparing a fix now.

**Comment by d99kris** [comment]
Thanks for reporting the bug @recrunchi - this should be fixed now.

**Comment by recrunchi** [comment]
> Thanks for reporting the bug @recrunchi - this should be fixed now.

Thanks to you d99kris!
