### ISSUE TITLE
compile error: ‘sort’ was not declared in this scope; did you mean ‘qsort’?

### ISSUE THREAD

**Issue by recrunchi** [d99kris/nchat#48]
hi. 

Yesterday i compiled it just fine, but today, after tdlib update, cannot compile.

I'm using the Low Memory / RAM Systems method, so i executed the "php SplitSource.php" command, and then start make with Release mode (i have a rpi4-4gb, without doing this, compilation aborts due to process being killed because out of memory)

Now i have this problem:

-------------
[ 78%] Building CXX object lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/StickersManager3.cpp.o
In file included from /data/nchat/lib/tgchat/ext/td/td/telegram/StickersManager2.cpp:46:
/data/nchat/lib/tgchat/ext/td/tdutils/td/utils/algorithm.h: In instantiation of ‘void td::unique(V&) [with V = std::vector<std::__cxx11::basic_string<char>, st
d::allocator<std::__cxx11::basic_string<char> > >]’:
/data/nchat/lib/tgchat/ext/td/td/telegram/StickersManager2.cpp:346:28:   required from here
/data/nchat/lib/tgchat/ext/td/tdutils/td/utils/algorithm.h:97:7: error: ‘sort’ was not declared in this scope; did you mean ‘qsort’?
   97 |   sort(v.begin(), v.end(), std::less<void>());
      |   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   qsort
make[2]: *** [lib/tgchat/ext/td/CMakeFiles/tdcore.dir/build.make:3296: lib/tgchat/ext/td/CMakeFiles/tdcore.dir/td/telegram/StickersManager2.cpp.o] Error 1
---------------

Thanks,
Sergio.

**Comment by d99kris** [comment]
Hi Sergio,
I suspect there could be some issue with `SplitSource.php`, but I'm not sure. I tested it locally on my machine, and it can compile. I don't have an ARM/GCC-based system to test on though.

Could you perhaps share some of the files that SplitSource generated
```
zip -r stickersmanager.zip lib/tgchat/ext/td/td/telegram/StickersManager*
``` 
and share it, for example by emailing to d99kris at gmail dot com (I don't think Github  Issues allows zip attachments?). Also if you could share output of `uname -a` and `g++ -v` it would be good.

To temporarily work around the issue, you could try one of the following:
1. Download the attached patch-algorithm.txt and apply it `git apply patch-algorithm.txt` in your `nchat` clone, and see if it fixes the compilation error.

2. Try install and build using `clang++` and try build without doing the SplitSource step. `clang++` uses less RAM and should be able to build on a 4 GB RAM system.
3.

**Comment by d99kris** [comment]
Hi again,
FYI - I did manage to get access to a Raspberry Pi 4 (4 GB) and it compiles latest `nchat` without issues. Irrespective of whether `SplitSource.php` has been used or not.

**Comment by d99kris** [comment]
I found an issue with the low memory systems build steps which I've fixed in the above commit.

I propose deleting your old clone (entire `nchat` directory) and do a fresh git clone and follow the updated steps in https://github.com/d99kris/nchat#low-memory--ram-systems

I suspect there was some old build artefacts from previous tdlib version, that might've caused the compilation error.

This issue has been closed now. Feel free to re-open for follow-up questions, or if the compilation error still persists.
