### ISSUE TITLE
does not send the code after entering the number

### ISSUE THREAD

**Issue by papuzha** [d99kris/nchat#52]
There was such a problem at startup
![Снимок экрана от 2022-01-09 17-10-00](https://user-images.githubusercontent.com/78297762/148685937-627e5aa0-8ceb-4ddd-8031-9379a93f778f.png)

**Comment by d99kris** [comment]
Hi @papuzha - the setup wizard first asks for which protocol you want to setup. At this prompt please enter `0` to set up nchat for Telegram. After this, nchat will ask for the phone number. 

I.e. the setup would be something like this:
```
$ nchat --setup
Protocols:
0. Telegram
1. Exit setup
Select protocol (1): 0
Enter phone number (ex. +6511111111): +79xxxxxxxxxxx
```
Let me know if you still encounter any problems.

(As a side-note, I should probably add better error handling for user input on that first prompt. Or possibly skip it altogether for nchat builds only supporting Telegram. I will look into that.)

**Comment by papuzha** [comment]
Thanks, everything worked

**Comment by d99kris** [comment]
> Thanks, everything worked

Thanks - good to hear! 

In the above commit I've also added better error handling for the user input, so that nchat does not crash.
