### ISSUE TITLE
[Feature Request] Desktop notification of new messages

### ISSUE THREAD

**Issue by jonnieey** [d99kris/nchat#54]
Would be great if there was a way to get notifications on new messages via a notification daemon.

**Comment by d99kris** [comment]
Support for this has been implemented in above commit. It is disabled by default, but can be enabled/configured using `desktop_notify_*` parameters in `ui.conf`, for example:

    desktop_notify_active=1
    desktop_notify_inactive=1

Refer to `README.md` for details.
