### ISSUE TITLE
Better shortcuts customization

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#60]
Tried to bind alt instead of ctrl for main tasks without luck.

**Comment by Bellavene** [comment]
Managed something with hex codes, but it glitches with registering custom keys only on second press of any next key

**Comment by Bellavene** [comment]
Temporary managed it with custom terminal profile, not the most elegant solution, but it works.

**Comment by d99kris** [comment]
As you mentioned in #12 there are capabilities for this implemented, but it's perhaps not easily accessible. 

I'll leave this issue open for now and see if we can improve the customization usability.

**Comment by Bellavene** [comment]
Thank you. iTerm has support for automatic profile switching per app. So you can bind any keys through it and manage them through custom profiles. If it helps somebody.
But I see a problem if you want to control nchat through ssh or terminal without support for such features.

**Comment by d99kris** [comment]
In commit 0239998 improved support for custom key bindings was implemented - enabling setting custom keys by their octal values.

Also, in commit 3bba971 a "key dump mode" was added - so if you start the program like this `nchat -k` it will just dump out the octal key values for any keys pressed. The intention is to make it easier to determine what values to put in ones `~/.nchat/key.conf`.

Let me know if you encounter any issues. Will proceed to close this issue now.
