### ISSUE TITLE
Custom mime types

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#63]
Would be awesome to be able to set custom scripts for files handling, like in "tg" for example.

```
# media
video/*; mpv "%s"
audio/ogg; mpv --speed=1.33 "%s"
audio/mpeg; mpv --no-video "%s"
image/*; qview "%s"

# text
text/html; w3m "%s"
text/html; open -a Firefox "%s"
text/plain; less "%s"

# fallback to vim
text/*; vim "%s"
```

Or at least a custom command to handle file previews. I want to set quicklook for that.

**Comment by d99kris** [comment]
Perhaps we can start with just adding support for custom command when opening files, as it should be fairly quick. If using command `see` (Linux) I believe mailcap directives would be used.

**Comment by Bellavene** [comment]
Custom command will do the job for me.

**Comment by d99kris** [comment]
Support for custom command has been added in above commit. It's configurable using `attachment_open_command` - check the README.md for details and example.
