### ISSUE TITLE
Crashes when window is too small

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#64]
Nchat crashes when terminal window has 5 or lower lines of text. With a tiling window manager there will be unexpected crashes.

**Comment by d99kris** [comment]
Thanks for reporting! This should be fixed in above commit. Let me know if there are still any issues related to this.

**Comment by Bellavene** [comment]
Thank you!

**Comment by Bellavene** [comment]
And thank you for the app overall. Game changer for me.
