### ISSUE TITLE
[Enhancement] Per user colors

### ISSUE THREAD

**Issue by rendiix** [d99kris/nchat#65]
In group chats, it's making it quite hard to distinguish who's who.

Even in 1on1 chats, it can get confusing.

Any way we can have random colors (or even predefined) colors on a user basis?

**Comment by d99kris** [comment]
Yeah, this has crossed my mind before too. Will take a look.

Note to self: Check how official Telegram client selects color - `getColorForId`?

**Comment by d99kris** [comment]
Do you have any example of terminal-based chat app that implements "per user color" with a nice UI? Would only the name have the special color, or both name and message text?

I'm thinking to start test out some implementation, and I'll google to check what other chat apps do, just thought I'd ask in case you know some good example.

**Comment by rendiix** [comment]
this is an example of a telegram cli that has implemented a per user color. 

[python-tg](https://github.com/paul-nameless/tg)

**Comment by d99kris** [comment]
Cool, thanks 👍

**Comment by rendiix** [comment]
> Cool, thanks 👍

Thanks for your hard work. I really like your project because it's really fast on my old machine

**Comment by d99kris** [comment]
Support for unique user colors in group chats has been added now. You can enable it for example by using the [Basic Color Theme](https://github.com/d99kris/nchat#basic-color-theme):
```
cp /usr/local/share/nchat/themes/basic-color/* ~/.nchat/
```
More specifically, nchat now supports the value `usercolor` for parameters `history_name_recv_group_color` and `history_text_recv_group_color`. When in group chats `usercolor` will be picked from `~/.nchat/usercolor.conf` based on a hash of the user id. Thus the actual colors used can be configured by editing that file (`usercolor.conf`).

Please let me know if you encounter any issues.

**Comment by rendiix** [comment]
@d99kris it works perfectly. thanks for the hard work

**Comment by rendiix** [comment]
per user color not working, has anyone experienced the same thing?

![Screenshot_2022-12-19-12-06-12-858_com termux](https://user-images.githubusercontent.com/16639978/208352539-c2c916bd-fd5e-4e5e-bf63-9a74bc266dd8.jpg)
![Screenshot_2022-12-19-12-07-05-287-edit_com termux](https://user-images.githubusercontent.com/16639978/208352555-c4df2329-406c-4e07-8ccd-988d44b81632.jpg)

**Comment by d99kris** [comment]
Hi @rendiix - would it be correct to say per-user colors works on some of your systems, and not on some others?

Could you please share a copy of `log.txt` after starting / stopping nchat on the machine were you see the problem?

**Comment by rendiix** [comment]
@d99kris Yes, per-user color in the last version didn't work on my machine. Previous version had no problem.

I run it on Android using Termux.

[log.txt](https://github.com/d99kris/nchat/files/10265035/log.txt)

**Comment by d99kris** [comment]
Thanks 👍  Hm, no obvious hints from the `log.txt`. 

Could you perhaps share a copy of your `~/.nchat/color.conf` and `~/.nchat/usercolor.conf` as well?

I don't have a working Termux installation at the moment, so I cannot easily test your setup, but per-user color is working for me on Ubuntu and macOS with latest nchat.

**Comment by rendiix** [comment]
My config file is not changed the same as provided by nchat by default.

this is precompiled nchat for termux arm64

[nchat_3.17_aarch64.zip](https://github.com/d99kris/nchat/files/10297906/nchat_3.17_aarch64.zip)

**Comment by rendiix** [comment]
Solved by installing the latest version of Termux, the crash comes from the Termux application itself.

**Comment by d99kris** [comment]
I assume the color problem was solved as well with latest Termux. Good to hear it worked out.
