### ISSUE TITLE
Connection status.

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#66]
Sometimes nchat, while opened, does not register new messages. Maybe add a connection status symbol somewhere?

**Comment by d99kris** [comment]
Have you disabled the top-bar (`ctrl-p`)? It should show connectivity status. 
Or is it indicating "Online" while still not receiving messages?

**Comment by Bellavene** [comment]
Yes, Ie disabled it. But the online status is written after the recipients name and there it was stuck while nchat wasn't online, that only happened two times.

**Comment by d99kris** [comment]
Improved connectivity status reporting was implemented in e55ec0e - now `nchat` should reflect the actual status. Will proceed to close this issue.
