### ISSUE TITLE
External file manager support

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#67]
Would be awesome if we could use ranger, nnn or etc. to pick up a file for sending. So we can preview them or find the needed one faster.

**Comment by d99kris** [comment]
Yeah, it's not a bad idea. Will see if I can leverage the external file picker support I implemented for [nmail](https://github.com/d99kris/nmail).

**Comment by Bellavene** [comment]
Thank You. Waiting for this the most, and for support of other messengers too!

**Comment by d99kris** [comment]
Hi! I finally got a chance to take a look at this. It's been implemented in above commit and is configurable using the new `file_picker_command` config parameter. Check the README.md for details / example.

**Comment by Bellavene** [comment]
Thank you!

**Comment by Bellavene** [comment]
Something went wrong for me

```
~/Downloads/nchat/mkdir -p build && cd build && cmake .. && make -s
-- Using build type 'RelWithDebInfo' (default).
-- Ncurses cmake prefix '/opt/homebrew/opt/ncurses' (detected).
-- Dummy: OFF
-- Telegram: ON
-- WhatsApp: ON
CMake Error at /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.2/share/cmake/Modules/FindSQLite3.cmake:54 (find_package_handle_standard_args)
  lib/ncutil/CMakeLists.txt:18 (find_package)
```

**Comment by d99kris** [comment]
That's odd, there haven't been any recent changes related to sqlite dependencies that I can recall.

Could you perhaps try making sure sqlite is installed `brew install sqlite` (assuming you're using brew)?

Also, in case you've used an old clone/checkout that you've updated, perhaps try deleting the old `build` directory, and retry the build command again.

**Comment by d99kris** [comment]
Good to hear! No worries! 👍
