### ISSUE TITLE
[Feature] Add support to standard io stream

### ISSUE THREAD

**Issue by CharlotteFallices** [d99kris/nchat#68]

**Comment by d99kris** [comment]
Hi @CharlotteFallices - could you please elaborate a little bit on this feature request? Perhaps give an example on how the it would work / what it's supposed to do?

The current title `Add support to standard io stream` with no further description is too vague for me to understand.

Thanks!

**Comment by CharlotteFallices** [comment]
I don't know exactly how to describe it :(
I mean something like `netcat`..... which allows us use it with other shell scripts 👀

**Comment by d99kris** [comment]
Thanks, I understand the request now.

Unfortunately the scope of `nchat` is only to be an interactive chat client. Command-line / automation usage are out-of-scope and not supported.

I'll proceed to close this issue.
