### ISSUE TITLE
[Feature Request] Custom server for new account

### ISSUE THREAD

**Issue by steven9463912** [d99kris/nchat#72]
Feature request: when adding a new account, let the user choose the ip/url of the endpoint of the telegram server, that way it will work also on custom servers

**Comment by d99kris** [comment]
Hi, I never heard about custom Telegram servers before. Any idea how to get access to such a server to test it, in case this feature is implemented?

Note though that this does not sound like a typical use-case to me, so I'm a little hesitant to add this support. 

If after all it's added, I think it'll be a "hidden" feature, by setting some env variable or something, so not to confuse the 99.9% normal users who don't want to use a custom server. 🙂

**Comment by d99kris** [comment]
I've done a little research and I couldn't find any API in `tdlib` (the official Telegram client library, that `nchat` uses) for using custom server hosts. Based on this and the fact that testing this feature would be cumbersome, I think I'll have have to consider this out of scope for nchat.

Will proceed to close this issue.
