### ISSUE TITLE
[Feature Request] Add support for editing messages

### ISSUE THREAD

**Issue by dikey0ficial** [d99kris/nchat#75]
I didn't found any hotkey in `--help` that allows to edit selected message. it's really important feature, though ;)

**Comment by d99kris** [comment]
Hi, nchat does not currently support editing messages.

This request has come up before though (in the https://t.me/nchatusers group IIRC), so maybe I'll check if it's simple to add.

**Comment by d99kris** [comment]
Telegram support for editing messages has been added in above commit.

Use key up/down to select message, and then press `ctrl-z` to start edit. Then `ctrl-x` saves the edit and `ctrl-c` cancels the edit. Note that only messages sent within last 48 hours is allowed to be edited.
