### ISSUE TITLE
Can't open in message links

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#77]
**Description**:
After update to latest version, whenever I try to open a link from a message, nchat only "blinks" and does nothing more.

**How to reproduce it**:
Don't know

**Environment**:
- Version: 3.16
- OS / distro: macos 13.0.1

**Comment by d99kris** [comment]
Hi @Bellavene - I tested here just now (also macOS 13.0.1) and I don't see the issue. Selecting a message and pressing `CTRL`-`w` opens any link(s) in the message.

Can I check what key binding you have for `open_link` in `~/.nchat/key.conf`? 
You can run `grep open_link ~/.nchat/key.conf` in the terminal to obtain it.

**Comment by Bellavene** [comment]
Hello Kristofer!

Yes, It is set as supposed to be. The screen just blinks to prompt in a millisecond and nothing.

Thank you

**Comment by d99kris** [comment]
Could you perhaps share a copy of your `~/.nchat/key.conf`? (you can just drag'n'drop into the comment field I think)

Basically I'd like to see if there is some key binding conflict.

**Comment by Bellavene** [comment]
Here you go. But as I sayd, I believe it is something else.

**Comment by d99kris** [comment]
Thank you. Yes, looks like you're right - this `key.conf` works fine for me.

Have you configured `attachment_open_command` in `~/.nchat/ui.conf`? Or is it empty?

One more thing to check could be if there's any log warning in `~/.nchat/log.txt` after you try opening a link? Nchat uses an external command to open links, and if that command fails, nchat logs something on this format:
```
cmd \"%s\" failed (%d)"
```

**Comment by d99kris** [comment]
Ok I see, I suppose we can add support in nchat for a separate config parameter like `link_open_command`, to make it more straight-forward to configure. Let me look into this.

As a temporary workaround you could create a wrapper shell script which detects if it's being passed an url or not.

**Comment by Bellavene** [comment]
Thank you. Would be useful if open links and open_command would be separated. But I can use a shell script as a workflow :)

**Comment by Bellavene** [comment]
Haha, we wrote the same things. Thank you

**Comment by d99kris** [comment]
Hi again, in the above commit support for configuring link open command separately has been added. The parameter is `link_open_command` in `~/.nchat/ui.conf`. Refer to README.md for more details.
