### ISSUE TITLE
How to disable alt+c and alt+a commands? They mess with Polish keyboard

### ISSUE THREAD

**Issue by MaciejWieczor** [d99kris/nchat#78]
I can't write some Polish signs because of the alt+c and alt+a key assingment. Is there any way to disable them? I tried just removing lines from the key.conf but it didn't seem to do anything

**Comment by MaciejWieczor** [comment]
Okay, after some searching I found that keys backspace and alt+c are mapped together, and right arrow key is mapped together with alt+a. 
I don't know if it is only my keyboard or not but that prevented me from writing in Polish normally 
Anyway I just mapped character deletion to ctrl+o and help to ctrl+h which now is quite usable, and I remapped the arrow keys to numpad keys so now Polish works for me.

**Comment by d99kris** [comment]
Hi @MaciejWieczor - glad to hear you found a solution. 

In any case, in the above commit I've added support for disabling key bindings by assigning them `KEY_NONE`. Perhaps it could be useful to someone.
