### ISSUE TITLE
Feature Requests and Suggestions

### ISSUE THREAD

**Issue by alohawolf** [d99kris/nchat#8]
Feature Request: Allow for contact search, or a way to show all contacts

Feature Request: Send Terminal bell (control-G) for messages in chat that has focus - in nchat if the chat has focus, its greedy and marks the message as read even if the app does not have focus - denying the user notification that they got a message if its running in the background

Suggestion: Change key mappings to use alt/meta as a default instead of control (control can interfere with use in screen/tmux - the only time control only is useful is when dealing with a real serial terminal the UTF8 support makes that unlikely) - also, change so enter is the default send message and shift-enter is the default insert a new line.

**Comment by d99kris** [comment]
Great feature requests and suggestions. I've split this issue into three new issues for each of the items to make it easier to track them independently. See links above. Will close this issue and track / respond to them separately.

**Comment by d99kris** [comment]
Issue #12 has been updated with a fix.

**Comment by d99kris** [comment]
Issue #11 has been updated with a fix.
