### ISSUE TITLE
rendering issues with emoji

### ISSUE THREAD

**Issue by alohawolf** [d99kris/nchat#9]
Some unicode characters cause rendering issues in various terminal emulators.

🔜 and 🐺 cause issues in putty+screen (and some in putty alone)

🇦🇺 🇻🇳 🇳🇱 🇮🇪 cause issues in terminal.app

The way this presents, is it seems to remove a character/space from the screen, so the line drawing characters get to be off by one when this happens.

**Comment by d99kris** [comment]
Hi @alohawolf - thanks for reporting the issue! 
It looks however as these issues are in the underlying OS/libraries. For example I did a quick "flag"-test in mc (midnight commander) and the same issue is seen there for the flag, but not for a normal "smiley". 
This stackoverflow-answer also gives some background on what is likely happening here:
https://stackoverflow.com/questions/54983257/curses-certain-emoji-flags-deform-terminal-output
Based on this I will proceed to close this issue. 
As a workaround you may use the "uilite" interface, which is impacted less by the issue, or try to disable emoji display (Ctrl-E).

**Comment by alohawolf** [comment]
I can no longer replicate the issues of flags breaking rendering, or any emoji for that matter - that said, neither setting uidefault emoji=0 or control-e seems to effect if emoji show up or not. I'll open a separate issue on that.

**Comment by d99kris** [comment]
Ok, I did make a fix related to utf-8 output in the contact list, which may or may have helped. Let's track the remaining issue(s) in #15.
