### ISSUE TITLE
can't type some words in Simplified Chinese

### ISSUE THREAD

**Issue by BennyThink** [d99kris/nchat#90]
**Description**:
can't type some specific words in simplified Chinese, no matter it's from copy paste or directly input. It will also erase the words before it.

**How to reproduce it**:
the word is `老`, sentence  `老师好`

https://user-images.githubusercontent.com/14024832/227161504-f2826f2d-a180-43af-b10f-e799e7a3d905.mp4

**Environment**:
- Version:
```
~ » nchat -v                                                                                                                                                           ~

nchat v3.39

Copyright (c) 2019-2023 Kristofer Berggren

nchat is distributed under the MIT license.

Written by Kristofer Berggren.
```
- OS / distro:
macOS Ventura 13.2.1 (22D68)

**Comment by BennyThink** [comment]
Thanks! Also this word `者` is the same. Guess they're the same issue

**Comment by d99kris** [comment]
Hi, the issue (including the second word mentioned) should be fixed in above commit. Please let me know if you're still seeing any issues. Thanks!

**Comment by BennyThink** [comment]
Thanks it works! It could be even better if there's any donation option(buy me a coffee, GitHub Sponsor, etc)

**Comment by d99kris** [comment]
Good to hear 👍  
I don't any have plans for accepting donations/sponsors at this point, but I'll update here if there are any changes to this. Thanks anyway 🙏
