### ISSUE TITLE
Terminal high CPU usage with latest release

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#93]
**Description**:
I have installed latest nchat and have noticed that iTerm while running nchat is constantly using 34% of the CPU.

**How to reproduce it**:
Install latest release.

**Environment**:
- Version: 3.39
- OS / distro: macOS 13.1

**Comment by d99kris** [comment]
Thanks for reporting the bug! I hadn't noticed it before in my testing, but I can see it now too. 

This degrade was probably introduced with commit 0f8ebd4 - will look into how to fix it.

**Comment by Bellavene** [comment]
No problem, it fixed another bug I had, but was lazy to report. There were text garbage left overs when you change contacts, I think this was caused by emojies, but maybe I am wrong.

**Comment by Bellavene** [comment]
This commit also messed up with non latin keyboard layouts, while typing on cyrillic, the caret moves far away from the actual place of text insertion.

**Comment by d99kris** [comment]
> This commit also messed up with non latin keyboard layouts, while typing on cyrillic, the caret moves far away from the actual place of text insertion.

Thanks for highlighting. I've reported a separate issue for this (see link above).

**Comment by d99kris** [comment]
This should be fixed now in above commit. Please let me know if you still encounter any issues.
