### ISSUE TITLE
Incorrect cursor position when entering Cyrillic characters

### ISSUE THREAD

**Issue by d99kris** [d99kris/nchat#94]
**Description**:
Incorrect cursor position when entering Cyrillic characters.
Issue highlighted by @Bellavene in #93 and also in `nchat users` telegram group.

**How to reproduce it**:
Enter some Cyrllic characters, for example: `водка`
Observe that the cursor position in the text entry field moves further than the text length.

**Environment**:
- Version: v3.40
- OS / distro: Both Linux and macOS affected.

**Comment by d99kris** [comment]
This issue was introduced with commit aa20da2 for #90.

**Comment by Bellavene** [comment]
водка балалайка
Thank's it works now 🥇
