### ISSUE TITLE
Add support for viewing stickers

### ISSUE THREAD

**Issue by d99kris** [d99kris/nchat#97]
### Discussed in https://github.com/d99kris/nchat/discussions/95

<div type='discussions-op-text'>

<sup>Originally posted by **Riteo** April 13, 2023</sup>
Hi! I really like this program and, although I don't know its architecture, a few things popped to mind.

Would it be possible to view the stickers? I can't seem to find a way. It looks like image stickers are WebP, video stickers are WebM and the animated vector ones are some weird https://github.com/TelegramMessenger/rlottie based thing.

All of them can be downloaded as files on the "regular" clients, so, unless this client archives them in some particular way, I think that it might be easy enough to make them viewable as regular files.

Again, mind that I have no actual idea on the feasibility of this proposal.

Another thing is that stickers have an emoji associated so I guess that a solution that's hopefully easier to implement would be to at least show the associated sticker next to the "sticker" text, kinda like how the "regular" clients do in their notifications, so that one could get at a glance what the sticker's probably going to express.</div>

**Comment by d99kris** [comment]
Support for viewing / downloading stickers have been added now for Telegram and WhatsApp.

In Telegram the equivalent emoji is shown in the message. Selecting a message (key up/down) and using `CTRL-V` opens the sticker in system default viewer, `CTRL-R` downloads the sticker.

**Comment by Docbroke** [comment]
Hi, can we do the same for animations/gif. I am only getting [animation] without "+" sign. Which cannot be viewed or downloaded.
btw., is there any simple viewer for .tgs files?

**Comment by d99kris** [comment]
Hi @Docbroke - good idea, I've added support for viewing Telegram animations now in 4b953cb.

Regarding `.tgs` viewer I am not aware of any simple viewer. I've come across [lottie-converter](https://github.com/ed-asriyan/lottie-converter) which maybe could be used to convert and then use another tool to view, but I'm not sure how "simple" that would be. I would maybe suggest to open a [Q&A discussion](https://github.com/d99kris/nchat/discussions/new?category=q-a) or ask in the [nchat users telegram group](https://t.me/nchatusers) - hopefully some other user may have some useful ideas.

**Comment by isottope** [comment]
tbh it's a hassle to view stickers like this way. any plan on rendering them (at least non animated ones) on the terminal using sixel ?
